### PR TITLE
Feature/add mocha tests tweaks

### LINKED ISSUE #10: Add creating resource test to Mocha
After we have Mocha installed (#9) we need to port the tests from the script suggested in #8 to Mocha.

**Acceptance criteria**

- [x] Running Mocha runs the create resource test
- [x] Running Mocha runs the push blob test
- [x] After Mocha is done, any created resource is deleted form CKAN server (provably an `afterEach` hook can cover that)

### PR DESCRIPTION
**Pull request by kmanaseryan**
Related issue: #9 

- Add frictionless and ckan-client-js libs into the project for the testing
- Add giftless url opton in cypress config - Once this gets merged make sure you update `cypress.json` accordingly.
- Create a basic test for pushing a blob with Mocha

### CODE REVIEW

**Review by cuducos — APPROVED** [review]
Great job! I will update the issues to keep track of what was covered in this PR, and I leave the merging for you both (@cotts included).

A minor comment:

I would prefer to have CKAN client and Fricitionless as dependencies (rather than development dependencies) because the aim of this repo is to be NPM-installed by other projects. Keeping these dependencies in `dependencies` instead of `devDependencies` avoids missing packages in this third parties, NPM-installed scenario.

For example: let's say the Government of Foo Bar Republic is my client and I install a CKAN instance for them. I can create a `ckan-foo-bar-uat` in which I would `npm install ckan-integration-tests` — keeping the CKAN client and Frictionless in `devDependencies` would not install these packages in my newly created repo, right?

**Comment by cuducos** [comment]
Closes #10

**Comment by kmanaseryan** [comment]
Great, thank you guys! I see the other commits here, thanks for the fixes @cotts 👍



> I would prefer to have CKAN client and Fricitionless as dependencies (rather than development dependencies) because the aim of this repo is to be NPM-installed by other projects. Keeping these dependencies in `dependencies` instead of `devDependencies` avoids missing packages in this third parties, NPM-installed scenario.
> 
> For example: let's say the Government of Foo Bar Republic is my client and I install a CKAN instance for them. I can create a `ckan-foo-bar-uat` in which I would `npm install ckan-integration-tests` — keeping the CKAN client and Frictionless in `devDependencies` would not install these packages in my newly created repo, right?

@cuducos OK, I got you, actually was not clear on this and put there in order to bring attention. So my point is that how we can make sure that the versions we use are the right ones? I mean if we have a client X who uses some CKAN app based on let's say React (e.g. [datapub](https://github.com/datopian/datapub)), which uses some specific version of `ckan-client-js` and `frictionless-js` then shouldn't we provide those libs from that app to our tests? Or alternatively those libs will be installed by that app. For example if we try to install [datapub](https://github.com/datopian/datapub) it will automatically install those libs, as those libs are already listed in the dependencies.

I think maybe instead of `devDependencies` we should use `peerDependencies`?

**Comment by cuducos** [comment]
Wow… didn't known about `peerDependencies` — sounds like a good use case for that!

**Pull request merged**
