### PR TITLE
Test sample

### PR DESCRIPTION
**Pull request by geoffrey1330**

### CODE REVIEW

**Review by ismail-shahzad — COMMENTED** [review]
Please add a little bit of description of what has been done in the PR and what has been fixed.

**Review by ismail-shahzad — CHANGES_REQUESTED** [review]
We don't need  the following files to be merged.

* `cypress/.DS_Store` (this shouldn't be uploaded at all as its your local file)
* `package-lock.json`
* `package.json`

**Comment by geoffrey1330** [comment]
> We don't need the following files to be merged.
> 
> * `cypress/.DS_Store` (this shouldn't be uploaded at all as its your local file)
> * `package-lock.json`
> * `package.json`

I've made the fix

**Comment by geoffrey1330** [comment]
For the PR: 
1. Fixed the datapusher integration test by changing `cy.get(':nth-child(2) > td').should('contain', 'Just now') ` to `cy.get(':nth-child(2) > td').contains(/Just now | seconds ago/i)` so as to or operation in getting expected outcome.

**Review by ismail-shahzad — APPROVED** [review]
LGTM

**Pull request merged**
